### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ritsuo7** [CivilTT/ServerStarter#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/121540542/211185307-1bb10804-dd09-420e-8ad1-2c4216c0e8e0.png)

**Comment by CivilTT** [comment]
ご連絡ありがとうございます！
返信が遅くなってしまい，失礼いたしました．

こちらのエラーは現在も発生していますでしょうか？
もし発生していましたら，恐れ入りますが詳細を確認させていただきたいので，ご連絡いただけますと幸いです！

**Comment by ritsuo7** [comment]
こんばんは！
こちらは再インストールしたら直り、解決いたしました。対応ありがとうございます。

**Comment by CivilTT** [comment]
それはよかったです！
今後ともServerStarterをご利用いただけますと幸いです！
